### ISSUE TITLE
Unable to 'go get' this package

### ISSUE THREAD

**Issue by lamielle** [cosiner/apidoc#1]
The apidoc.go file imports a private repository, github.com/cosiner/golib, which I'm unable to access.

I'd love to try out your tool but at this point I'm unable to do so.  Could you please expose this 'golib' dependency? Thanks!

**Comment by cosiner** [comment]
I'm sorry, i change the name of 'golib' package yesterday, but forgot push it to github.
Now it was fixed, thanks for your attention.

**Comment by lamielle** [comment]
No problem, I had this in my TODO list for projects to look into.  I'll give it a shot today!  Thanks for the quick response!
